### ISSUE TITLE
[Bug] assert loss failed

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternEvo#114]
### Describe the bug

Deatials:
https://github.com/InternLM/InternEvo/actions/runs/8395156088

### Environment

python3.10

**Comment by kkscilife** [comment]
others:
https://github.com/InternLM/InternEvo/actions/runs/8430382349

**Comment by li126com** [comment]
最新代码可通

**Comment by kkscilife** [comment]
The weekly test still faild: https://github.com/InternLM/InternEvo/actions/runs/8574468442

**Comment by kkscilife** [comment]
Resolved!
https://github.com/InternLM/InternEvo/actions/runs/8700052838/job/23860882032
