### ISSUE TITLE
[Feature] do not export the global variable  internlm_accelerator

### ISSUE THREAD

**Issue by sunpengsdu** [InternLM/InternEvo#128]
### Describe the feature

<img width="344" alt="image" src="https://github.com/InternLM/InternEvo/assets/6859848/b4ccf9a7-6bba-4fd3-ba98-be41bbe8da95">
do not export the global variable  internlm_accelerator, always use get_accelerator() to get the accelerator

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by sallyjunjun** [comment]
https://github.com/InternLM/InternEvo/pull/133
