### ISSUE TITLE
[Feature] use consist way for get device

### ISSUE THREAD

**Issue by sunpengsdu** [InternLM/InternEvo#137]
### Describe the feature

currently we use several ways to get device

- internlm_accelerator.device()
- internlm_accelerator.current_device()
- from internlm.utils.common import get_current_device

we should the consist way to perform the get_device operation.

In addition, the interface " internlm_accelerator.device()" is necessary?

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by li126com** [comment]
https://github.com/InternLM/InternEvo/pull/139/files
