### ISSUE TITLE
[Bug] internlm docker image issue

### ISSUE THREAD

**Issue by marks221b** [InternLM/InternEvo#182]
### Describe the bug

The container version of internlm has not been built successfully. After pulling the image and entering the container, it was found that it is not possible to directly use the container for training and inference. The environment inside the container also differs significantly from the actual runtime environment needed.

### Environment

The container version of internlm has not been built successfully. After pulling the image and entering the container, it was found that it is not possible to directly use the container for training and inference. The environment inside the container also differs significantly from the actual runtime environment needed.

**Comment by sunpengsdu** [comment]
please update the docker file with lasted requirements. @li126com

**Comment by li126com** [comment]
New docker images are ready at https://hub.docker.com/r/internlm/internevo/tags.  The relative docs in the InternEvo have been updated.
