### ISSUE TITLE
[Bug]  IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternEvo#215]
### Describe the bug

There is a new error in weekly test:
![image](https://github.com/InternLM/InternEvo/assets/126147887/8ad5db7d-be4c-45f6-937e-9c2012168fb0)
Details:
https://github.com/InternLM/InternEvo/actions/runs/9036801596/job/24836640280

### Environment

python 3.10
torch 2.1

**Comment by li126com** [comment]
https://github.com/InternLM/InternEvo/pull/217 ，已修复
