### ISSUE TITLE
[Bug] TypeError: record_current_batch_training_metrics() missing 1 required positional argument: 'very_begining_time'

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternEvo#223]
### Describe the bug

<img width="455" alt="企业微信截图_1716172518762" src="https://github.com/InternLM/InternEvo/assets/126147887/6081e2a9-f11d-4e60-8132-064fa305e62d">
Details: https://github.com/InternLM/InternEvo/actions/runs/9125368958/job/25098842355

### Environment

python3.10
torch2.1

**Comment by li126com** [comment]
https://github.com/InternLM/InternEvo/pull/227/files ，fix
