### ISSUE TITLE
[QA] 使用InternLM pretrain llama2-7b之后，怎么用训练之后的模型做推理？

### ISSUE THREAD

**Issue by wen020** [InternLM/InternEvo#259]
### 描述问题

使用InternLM pretrain llama2-7b之后，怎么用训练之后的模型做推理？我们尝试使用https://github.com/InternLM/InternEvo/blob/develop/web_demo_internlm.py#L65 这个脚本，更新load_model方法去加载llama2-7b，但是在运行时报如下错误，请问我们该怎么用训练之后的llama2模型去做推理？
![image](https://github.com/InternLM/InternEvo/assets/54690997/e6855253-7868-4a41-a5bf-f0cd73085c07)

**Comment by gaoyang07** [comment]
您好，我们提供了一个推理脚本，请参考 #260
