### ISSUE TITLE
[Bug] 昇腾910安装internLM环境时报错需要nvcc

### ISSUE THREAD

**Issue by tungsten106** [InternLM/InternEvo#298]
### 描述该错误

$ pip install InternEvo
Collecting InternEvo
  Downloading InternEvo-0.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting transformers<4.30.0 (from InternEvo)
  Downloading transformers-4.29.2-py3-none-any.whl.metadata (112 kB)
Collecting sentencepiece (from InternEvo)
  Downloading sentencepiece-0.2.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (7.7 kB)
Requirement already satisfied: numpy in /root/miniconda3/envs/torch_npu/lib/python3.10/site-packages (from InternEvo) (1.26.4)
Collecting tqdm (from InternEvo)
  Downloading tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: psutil in /root/miniconda3/envs/torch_npu/lib/python3.10/site-packages (from InternEvo) (6.0.0)
Collecting packaging (from InternEvo)
  Downloading packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pre-commit (from InternEvo)
  Downloading pre_commit-3.8.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting ninja (from InternEvo)
  Downloading ninja-1.11.1.1-py2.py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata (5.3 kB)
Collecting gputil (from InternEvo)
  Downloading GPUtil-1.4.0.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
Collecting pytest (from InternEvo)
  Downloading pytest-8.3.2-py3-none-any.whl.metadata (7.5 kB)
Collecting boto3 (from InternEvo)
  Downloading boto3-1.34.159-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore (from InternEvo)
  Downloading botocore-1.34.159-py3-none-any.whl.metadata (5.7 kB)
Collecting pyecharts (from InternEvo)
  Downloading pyecharts-2.0.6-py3-none-any.whl.metadata (1.3 kB)
Collecting py-libnuma (from InternEvo)
  Downloading py_libnuma-1.2-py3-none-any.whl.metadata (3.0 kB)
Collecting pynvml (from InternEvo)
  Downloading pynvml-11.5.3-py3-none-any.whl.metadata (8.8 kB)
Collecting tensorboard (from InternEvo)
  Downloading tensorboard-2.17.0-py3-none-any.whl.metadata (1.6 kB)
Collecting rotary-emb (from InternEvo)
  Downloading rotary_emb-0.5.2.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5lvk869c/rotary-emb_d0707a936625419183e4f10e232debec/setup.py", line 90, in <module>
          raise_if_cuda_home_none("rotary_emb")
        File "/tmp/pip-install-5lvk869c/rotary-emb_d0707a936625419183e4f10e232debec/setup.py", line 44, in raise_if_cuda_home_none
          raise RuntimeError(
      RuntimeError: rotary_emb was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
      
      Warning: Torch did not find available GPUs on this system.
       If your intention is to cross-compile, this is not an error.
      By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
      Volta (compute capability 7.0), Turing (compute capability 7.5),
      and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
      If you wish to cross-compile for a single specific architecture,
      export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

### 环境信息

```
torch==2.1.0  
torch-npu==2.1.0.post3
python==3.10
CANN 8.0.RC1
```
安装方法如下：
```
pip install torch==2.1.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
pip3 install torch-npu==2.1.0.post3
Looking in indexes: https://download.pytorch.org/whl/cpu
```

### 其他信息

环境安装好后执行到 `pip install InternEvo` 时报错。已配置好torch和torch-npu环境。

**Comment by sunpengsdu** [comment]
@li126com

**Comment by li126com** [comment]
pip install InternEvo目前仅支持GPU，NPU可以源码安装InternEvo。后续会加一个可选项对rotary_emb 的安装
