### ISSUE TITLE
[Bug] There is an error in training : built-in model should inherited from BaseModel

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternEvo#318]
### Describe the bug

There is an error in training : built-in model should inherited from BaseModel
![img_v3_02ei_dddb0bf7-ae85-4eda-a462-39625c74dffg](https://github.com/user-attachments/assets/100c2a73-3525-41a5-bb07-c33171452704)
 Details: https://github.com/InternLM/InternEvo/actions/runs/10743746443/job/29801300473

### Environment

python3.10
torch2.1

**Comment by zigzagcai** [comment]
Update:

fixed in https://github.com/InternLM/InternEvo/pull/319
