### ISSUE TITLE
请问是否支持internLM2[QA] 

### ISSUE THREAD

**Issue by Labmem009** [InternLM/InternEvo#32]
### Describe the question.

目前在internLM2的教程中只有XTuner版本的，InternEvo的版本尚未发布吗，请问有计划什么时候发布吗？请问InternEVO相对于XTuner的区别在哪？

**Comment by gaoyang07** [comment]
InternLM2 的模型将在这周内合入 InternEvo，参考 [pr15](https://github.com/InternLM/InternEvo/pull/15)，届时您可以使用 InternEvo 框架直接微调 InternLM2
