### ISSUE TITLE
[Bug] OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternEvo#86]
### Describe the bug

Details：https://github.com/InternLM/InternEvo/actions/runs/8301063319/job/22722755612
<img width="550" alt="企业微信截图_17107289923227" src="https://github.com/InternLM/InternEvo/assets/126147887/db33a42d-b5a0-4e9d-8ce5-1093b1a0abf7">

### Environment

python 3.10

**Comment by li126com** [comment]
https://github.com/InternLM/InternEvo/pull/89，已修复
