### ISSUE TITLE
[Bug] parallel output may be error in no flashattention case

### ISSUE THREAD

**Issue by sunpengsdu** [InternLM/InternEvo#97]
### 描述该错误

<img width="400" alt="image" src="https://github.com/InternLM/InternEvo/assets/6859848/3998efe0-2c0f-49ce-9192-82a4bae3d0c8">
parallel output may be error in no flashattention case

### 环境信息

no flashattention case

**Comment by sunpengsdu** [comment]
<img width="682" alt="企业微信截图_d9c1be4b-a3ee-4146-bfeb-fecf98e5165b" src="https://github.com/InternLM/InternEvo/assets/6859848/ae201cdc-19fe-470a-8bc9-896b6b14e60c">

**Comment by sunpengsdu** [comment]
here is a hard-code

**Comment by huangting4201** [comment]
completed in pr #103
